version: "3.7"
services:
  web:
    build: .
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
